const crypto = require('crypto');

/**
 * MySQL has no RETURNING clause, so identifiers are generated by the
 * application and passed explicitly on INSERT.
 */
const newId = () => crypto.randomUUID();

module.exports = { newId };
